#!/bin/sh

sleep 0.1 # wait briefly for xdpw pipewire object to spawn

export OUTPUT=$1
export CHOICE=$2

export RULE=`pw-link -lI | tail -n2 | awk 'ORS="," {print $3","$1}'`
grep -q $RULE /dev/shm/sway-wscap-pwlinks && exit 1
echo -n $RULE >> /dev/shm/sway-wscap-pwlinks

if [ $CHOICE -eq 1 ]
then
	swaymsg -t get_workspaces | jq ".[] | select(.visible) | select(.output==\"$OUTPUT\") | .num" \
    	>> /dev/shm/sway-wscap-pwlinks
else
	echo , >> /dev/shm/sway-wscap-pwlinks
fi
