#!/bin/sh

export GET_OUTPUTS=`swaymsg -t get_outputs`
if [ `echo $GET_OUTPUTS | jq length` -eq 1 ]
then
	export OUTPUT=`echo $GET_OUTPUTS | jq -r '.[] | .name'`
else
	export OUTPUT=`slurp -f %o -or`
fi
[ -z $OUTPUT ] && exit 1
echo $OUTPUT

swaymsg focus output $OUTPUT # fixes weird bug, dont ask

# keep shm file tidy
export INLINKS=`pw-link -iI | awk '{print $1}'`
for i in `cat /dev/shm/sway-wscap-pwlinks`
do
	echo $INLINKS | grep -q `echo $i | awk -F, '{print $2}'` \
		|| sed -i "/$i/d" /dev/shm/sway-wscap-pwlinks
done

export CHOICE=$(
	swaynag -t warning -m 'Choose what to capture:' \
			-s 'Capture entire output' \
			-z 'Just this workspace' 'echo 1' \
				&>/dev/null
)

[ -n $CHOICE ] && `dirname $0`/sway-wscap $OUTPUT $CHOICE &
