#!/bin/sh

export OUTPUT=`slurp -f %o -or`
[ -z $OUTPUT ] && exit 1
echo $OUTPUT

swaymsg focus output $OUTPUT # fixes weird bug, dont ask

export CHOICE=$(
	swaynag -t warning -m 'Choose what to capture:' \
			-s 'Capture entire output' \
			-z 'Just this workspace' 'echo 1' \
				&>/dev/null
)

[ -n $CHOICE ] && `dirname $0`/sway-wscap $OUTPUT $CHOICE &
