#!/bin/sh
set -x

sleep 0.1 # wait briefly for xdpw pipewire object to spawn

export OUTPUT=$1
export CHOICE=$2

pw-link -lI | tail -n2 | awk 'ORS="," {print $3","$1}' \
	>> /dev/shm/sway-wscap-pwlinks

if [ $CHOICE -eq 1 ]
then
	swaymsg -t get_workspaces | jq ".[] | select(.visible) | select(.output==\"$OUTPUT\") | .num" \
    	>> /dev/shm/sway-wscap-pwlinks
else
	echo , >> /dev/shm/sway-wscap-pwlinks
fi
